### PR TITLE
fix error thrown when tagName has not yet been defined on a component

### LINKED ISSUE #19: You cannot use `attributeBindings` on a tag-less component
I've just migrated my application to ember.js 2.8 and it started throwing error in the console.

`Uncaught Error: Assertion Failed: You cannot use attributeBindings on a tag-less component: <yyyyyy@component:xxxxx::ember382>`

Due to this error, the app doesn't load and shows an empty page.

I've created a small demo app with just ember-hammertime and a tagless component and it still throws the same error: https://github.com/thagul/hammertime-2-8
To verify just run the app and check the console.

### PR DESCRIPTION
**Pull request by eriktrom**
- has to do with with glimmer2 component instantiation differing from
  glimmer1 (even without glimmer flag enabled)
- affects concatenated properties and apply mixin logic in ember metal
- source of actual difference in code paths unknown ATM

fixes #19

### CODE REVIEW

File: addon/mixins/touch-action.js [hunk 1]
```diff
@@ -45,8 +45,12 @@ export default Mixin.create({
       click
     } = this;
 
-    let maybeApplyStyle = ignoreTouchAction === false && tagName !== '';
-    let hasClickHandler = ignoreTouchAction === false && click !== K;
+    const hasClick = click !== K;
+    const hasTag = (typeof tagName === 'string' && tagName.length > 0) || (tagName === null && hasClick);
+    if (!hasTag) { return; }
+
+    let maybeApplyStyle = ignoreTouchAction === false && hasTag;
```
Comment (runspired) [inline addon/mixins/touch-action.js]: we don't need `&& hasTag` here since we return eagerly above.

Comment (eriktrom) [inline addon/mixins/touch-action.js]: thanks :)

**Comment by eriktrom** [comment]
ready to ⛵ 

closing notes - the original code with the check for tagName is likely sufficient - we may want to simplify(or figured you'd want to know that we dont need the meta-programming down there - although it looks like it may allow combining styles from more than one mixin 'mixed in' to one component - so might be cool - haven't tried though - anyway - just fyi)

**Comment by runspired** [comment]
I'll tag a new release tonight, if you have another moment to figure out what is making the test harness choke on travis that's also appreciated :)

**Comment by eriktrom** [comment]
yeah dont tag a release - it seems to be adding to many touch-action attrs - something the other brranch was not doing - let me code for a bit with it tonight - will ping u back

**Comment by jakeleboeuf** [comment]
Any update on this?

**Comment by eriktrom** [comment]
Fixed and released in 1.12
